// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Zoxgo-huVQEWhZlHUv8tqkAAbGxra8g',
    appId: '1:716098796396:web:dd200d928e5e90f873d149',
    messagingSenderId: '716098796396',
    projectId: 'fastbiteus-ae5ab',
    authDomain: 'fastbiteus-ae5ab.firebaseapp.com',
    storageBucket: 'fastbiteus-ae5ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXdQTfHLWrrJLYm2IDcMc-JGKAJ1kC7iM',
    appId: '1:716098796396:android:98159a2e470dfdb973d149',
    messagingSenderId: '716098796396',
    projectId: 'fastbiteus-ae5ab',
    storageBucket: 'fastbiteus-ae5ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxUZd7vVKPxcK7t7Dpb9RIAw_7BfpliIQ',
    appId: '1:716098796396:ios:1bb23dc2d035f6ca73d149',
    messagingSenderId: '716098796396',
    projectId: 'fastbiteus-ae5ab',
    storageBucket: 'fastbiteus-ae5ab.appspot.com',
    iosBundleId: 'com.sixamtech.stackFoodRestaurant',
  );
}
